CREATE INDEX idx_crime_city_type ON crime_scene_report(city, type);
CREATE INDEX idx_person_license ON person(license_id);
CREATE INDEX idx_person_ssn ON person(ssn);
CREATE INDEX idx_checkin_date ON get_fit_now_check_in(check_in_date);
CREATE INDEX idx_checkin_membership ON get_fit_now_check_in(membership_id);
CREATE INDEX idx_member_status ON get_fit_now_member(membership_status);
CREATE INDEX idx_member_person ON get_fit_now_member(person_id);
CREATE INDEX idx_facebook_date ON facebook_event_checkin(date);
CREATE INDEX idx_facebook_person ON facebook_event_checkin(person_id);
CREATE INDEX idx_drivers_hair_make ON drivers_license(hair_color, car_make);
CREATE INDEX idx_person_name ON person(name);